name: 功能建议
description: 描述希望解决的使用问题
title: "[Feature] "
body:
  - type: textarea
    id: problem
    attributes:
      label: 遇到了什么问题？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 希望如何改进？
    validations:
      required: true
